name: Build & Deploy St Catherine's Group Website
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'web/sites/stcatherinesgroup.com/**'
      - 'web/package.json'
      - 'web/pnpm-lock.yaml'
      - 'web/pnpm-workspace.yaml'
      - 'web/libs/**'
      - '.github/workflows/web/site-stcatherinesgroup.yml'
      - '.github/workflows/site-template.yml'

jobs:
  jamesdurban:
    name: "Build & Deploy stcatherinesgroup.com"
    uses: ./.github/workflows/site-template.yml
    with:
      site: stcatherinesgroup.com
    secrets:
      server_host: ${{ secrets.HOST }}
      server_username: ${{ secrets.USERNAME }}
      server_password: ${{ secrets.PASSWORD }}
      server_ssh_port: ${{ secrets.PORT }}