name: thecontourclinicrichmond
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'sites/thecontourclinicrichmond.co.uk/**'
      - '.github/workflows/sites/site-thecontourclinicrichmond.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'sites/thecontourclinicrichmond.co.uk/**'
      - '.github/workflows/sites/site-thecontourclinicrichmond.yml'

jobs:
  thecontourclinicrichmond:
    name: "Build & Deploy thecontourclinicrichmond.co.uk"
    uses: james-d12/Websites/.github/workflows/site-template.yml@main
    with:
      site: thecontourclinicrichmond.co.uk
    secrets:
      server_host: ${{ secrets.SERVER_HOST }}
      server_username: ${{ secrets.SERVER_USERNAME }}
      server_password: ${{ secrets.SERVER_PASSWORD }}
      server_ssh_port: ${{ secrets.SERVER_SSH_PORT }}