name: jamesdurban
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'sites/jamesdurban.com/**'
      - '.github/workflows/sites/site-jamesdurban.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'sites/jamesdurban.com/**'
      - '.github/workflows/sites/site-jamesdurban.yml'

jobs:
  jamesdurban.com:
    name: "Build & Deploy jamesdurban.com"
    uses: ./site-template.yml
    with:
      site: jamesdurban.com
    secrets:
      server_host: ${{ secrets.SERVER_HOST }}
      server_username: ${{ secrets.SERVER_USERNAME }}
      server_password: ${{ secrets.SERVER_PASSWORD }}
      server_ssh_port: ${{ secrets.SERVER_SSH_PORT }}