name: Build and Deploy James Durban Website
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'sites/jamesdurban.com/**'
      - '.github/workflows/site-jamesdurban.yml'
      - '.github/workflows/site-template.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'sites/jamesdurban.com/**'
      - '.github/workflows/site-jamesdurban.yml'
      - '.github/workflows/site-template.yml'

jobs:
  jamesdurban:
    name: "Build & Deploy jamesdurban.com"
    uses: james-d12/Websites/.github/workflows/site-template.yml@main
    with:
      site: jamesdurban.com
    secrets:
      server_host: ${{ secrets.SERVER_HOST }}
      server_username: ${{ secrets.SERVER_USERNAME }}
      server_password: ${{ secrets.SERVER_PASSWORD }}
      server_ssh_port: ${{ secrets.SERVER_SSH_PORT }}