packages:
  - libs/*
  - sites/*

auditConfig: {}

minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'tinyclip@0.1.13'
  - 'chokidar@4.0.3'
  - 'semver@6.3.1'
blockExoticSubdeps: true
